[build-system]
requires = ["hatchling >= 1.26","pyodbc","json","re","time","socket","select","multiprocessing","queue","typing","json","datetime","traceback","sys","os","csv"]
build-backend = "hatchling.build"